using System;
using System.Collections.Generic;
using System.Globalization;
using Npgsql;
using Win11DesktopApp.EmployeeModels;

namespace Win11DesktopApp.Services
{
    public sealed class PostgresArchiveLogStorage : IArchiveLogStorage
    {
        private readonly AppSettingsService _settingsService;
        private readonly object _initLock = new();
        private bool _isInitialized;

        public PostgresArchiveLogStorage(AppSettingsService settingsService)
        {
            _settingsService = settingsService ?? throw new ArgumentNullException(nameof(settingsService));
        }

        public LocalDbMigrationResult MigrateArchiveLogIfNeeded(string jsonPath, IReadOnlyList<ArchiveLogEntry> sourceEntries)
        {
            return new LocalDbMigrationResult
            {
                WasMigrationAttempted = false,
                IsSuccessful = true,
                RecordsFound = sourceEntries?.Count ?? 0,
                RecordsImported = 0,
                Message = "PostgreSQL archive log is populated by the SQLite to PostgreSQL migration wizard."
            };
        }

        public List<ArchiveLogEntry> GetAllArchiveLogs()
        {
            EnsureInitialized();
            using var connection = OpenConnection();
            using var command = connection.CreateCommand();
            command.CommandText = @"
SELECT operation_id, employee_name, firm_name, employee_folder, action, date, timestamp,
       is_reverted, reverted_at, reverted_by_operation_id
FROM app.archive_log
ORDER BY timestamp DESC, id DESC;";

            using var reader = command.ExecuteReader();
            var result = new List<ArchiveLogEntry>();
            while (reader.Read())
                result.Add(ReadArchiveLogEntry(reader));

            return result;
        }

        public ArchiveLogEntry? GetActiveArchiveLogEntry(string operationId)
        {
            EnsureInitialized();
            if (string.IsNullOrWhiteSpace(operationId))
                return null;

            using var connection = OpenConnection();
            using var command = connection.CreateCommand();
            command.CommandText = @"
SELECT operation_id, employee_name, firm_name, employee_folder, action, date, timestamp,
       is_reverted, reverted_at, reverted_by_operation_id
FROM app.archive_log
WHERE operation_id = @operationId
  AND lower(action) = 'archived'
  AND is_reverted = 0
LIMIT 1;";
            command.Parameters.AddWithValue("operationId", operationId);

            using var reader = command.ExecuteReader();
            return reader.Read() ? ReadArchiveLogEntry(reader) : null;
        }

        public void InsertArchiveLog(ArchiveLogEntry entry)
        {
            EnsureInitialized();
            using var connection = OpenConnection();
            using var transaction = connection.BeginTransaction();
            InsertArchiveLog(connection, transaction, entry);
            transaction.Commit();
        }

        public bool MarkArchiveLogReverted(string operationId, string undoOperationId)
        {
            EnsureInitialized();
            if (string.IsNullOrWhiteSpace(operationId))
                return false;

            using var connection = OpenConnection();
            using var command = connection.CreateCommand();
            command.CommandText = @"
UPDATE app.archive_log
SET is_reverted = 1,
    reverted_at = @revertedAt,
    reverted_by_operation_id = @undoOperationId
WHERE operation_id = @operationId
  AND is_reverted = 0;";
            command.Parameters.AddWithValue("revertedAt", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture));
            command.Parameters.AddWithValue("undoOperationId", undoOperationId ?? string.Empty);
            command.Parameters.AddWithValue("operationId", operationId);
            return command.ExecuteNonQuery() > 0;
        }

        private void EnsureInitialized()
        {
            if (_isInitialized)
                return;

            lock (_initLock)
            {
                if (_isInitialized)
                    return;

                using var connection = OpenConnection();
                using var command = connection.CreateCommand();
                command.CommandText = @"
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.archive_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id TEXT NOT NULL,
    employee_name TEXT NOT NULL,
    firm_name TEXT NOT NULL,
    employee_folder TEXT NOT NULL,
    action TEXT NOT NULL,
    date TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    is_reverted INTEGER NOT NULL DEFAULT 0,
    reverted_at TEXT,
    reverted_by_operation_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_pg_archive_log_operation_id ON app.archive_log(operation_id);
CREATE INDEX IF NOT EXISTS idx_pg_archive_log_is_reverted ON app.archive_log(is_reverted);
CREATE INDEX IF NOT EXISTS idx_pg_archive_log_timestamp ON app.archive_log(timestamp DESC);";
                command.ExecuteNonQuery();
                _isInitialized = true;
            }
        }

        private static void InsertArchiveLog(NpgsqlConnection connection, NpgsqlTransaction transaction, ArchiveLogEntry entry)
        {
            using var command = connection.CreateCommand();
            command.Transaction = transaction;
            command.CommandText = @"
LOCK TABLE app.archive_log IN EXCLUSIVE MODE;

INSERT INTO app.archive_log (
    id, operation_id, employee_name, firm_name, employee_folder, action, date, timestamp,
    is_reverted, reverted_at, reverted_by_operation_id
) VALUES (
    (SELECT COALESCE(MAX(id), 0) + 1 FROM app.archive_log),
    @operationId, @employeeName, @firmName, @employeeFolder, @action, @date, @timestamp,
    @isReverted, @revertedAt, @revertedByOperationId
);";
            command.Parameters.AddWithValue("operationId", entry.OperationId ?? string.Empty);
            command.Parameters.AddWithValue("employeeName", entry.EmployeeName ?? string.Empty);
            command.Parameters.AddWithValue("firmName", entry.FirmName ?? string.Empty);
            command.Parameters.AddWithValue("employeeFolder", entry.EmployeeFolder ?? string.Empty);
            command.Parameters.AddWithValue("action", entry.Action ?? string.Empty);
            command.Parameters.AddWithValue("date", entry.Date ?? string.Empty);
            command.Parameters.AddWithValue("timestamp", entry.Timestamp ?? string.Empty);
            command.Parameters.AddWithValue("isReverted", entry.IsReverted ? 1 : 0);
            command.Parameters.AddWithValue("revertedAt", (object?)entry.RevertedAt ?? DBNull.Value);
            command.Parameters.AddWithValue("revertedByOperationId", (object?)entry.RevertedByOperationId ?? DBNull.Value);
            command.ExecuteNonQuery();
        }

        private static ArchiveLogEntry ReadArchiveLogEntry(NpgsqlDataReader reader)
        {
            return new ArchiveLogEntry
            {
                OperationId = reader.IsDBNull(0) ? string.Empty : reader.GetString(0),
                EmployeeName = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                FirmName = reader.IsDBNull(2) ? string.Empty : reader.GetString(2),
                EmployeeFolder = reader.IsDBNull(3) ? string.Empty : reader.GetString(3),
                Action = reader.IsDBNull(4) ? string.Empty : reader.GetString(4),
                Date = reader.IsDBNull(5) ? string.Empty : reader.GetString(5),
                Timestamp = reader.IsDBNull(6) ? string.Empty : reader.GetString(6),
                IsReverted = !reader.IsDBNull(7) && reader.GetInt32(7) != 0,
                RevertedAt = reader.IsDBNull(8) ? null : reader.GetString(8),
                RevertedByOperationId = reader.IsDBNull(9) ? null : reader.GetString(9)
            };
        }

        private NpgsqlConnection OpenConnection()
        {
            var settings = _settingsService.Settings;
            var builder = new NpgsqlConnectionStringBuilder
            {
                Host = string.IsNullOrWhiteSpace(settings.PostgresHost) ? "localhost" : settings.PostgresHost.Trim(),
                Port = settings.PostgresPort <= 0 ? 5432 : settings.PostgresPort,
                Database = string.IsNullOrWhiteSpace(settings.PostgresDatabase) ? "agency_db" : settings.PostgresDatabase.Trim(),
                Username = string.IsNullOrWhiteSpace(settings.PostgresUsername) ? "postgres" : settings.PostgresUsername.Trim(),
                Password = LocalSecretProtection.Unprotect(settings.EncryptedPostgresPassword),
                Timeout = 10,
                CommandTimeout = 30,
                Pooling = true
            };

            var connection = new NpgsqlConnection(builder.ConnectionString);
            connection.Open();
            return connection;
        }
    }
}
